### ISSUE TITLE
Warby Parker Project Summary & Rubric Score

### ISSUE THREAD

**Issue by karl-project-review** [ArthurNicholas/sql-scratch-capstone-turn-in#5]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all answers?
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ All of your conclusions are clearly stated and supported by the results of your provided queries. Well done! While there is an issue with your recommendation about sticking with the 3-pair trial, this is due to a mistake in the query (see: issue #1), and not a problem with the report. 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 3/4 (Meets Expectations) 
* _Comment(s):_ Most of your queries retrieve the rows and information that they should. However, as discussed in issue #1, the query that is supposed to retrieve the number of purchases for the 3-pair trial group and the 5-pair trial group actually just retrieves the number of people in each trial group, which results in an erroneous conclusion being drawn about the amount of difference between these numbers.
### Criteria 3: Query Formatting
* _Score Level:_ 3/4 (Meets Expectations)
* _Comment(s):_ Your code adheres to many of our SQL formatting guidelines. However, there are issues with reserved keywords not being in all capital letters (issue #2), an extraneous LIMIT line (issue #3), and indentation (issue #4).  
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4 (Exceeds Expectations)
* _Comment(s):_ Your report demonstrates an understanding of both the quiz and purchase funnels. Good work!

### Overall Score: 14/16 (Meets Expectations)
Nice job on this overall! Most of your queries do what they should, and you interpreted the results of those queries appropriately. My primary recommendation for you moving forward is to be careful when working with joined tables that have columns with the same name not to select columns from the wrong table (as was the problem with the 3 vs 5 trial group query). Examining a few rows of the joined tables using LIMIT before writing the final query can help to prevent this. Again, well done overall!

**Comment by ArthurNicholas** [comment]
Thank you for your review.  I will continue to work with CodeAcademy

**Comment by ArthurNicholas** [comment]
My employer has asked for a certificate of completion for this course.  Is there a certificate or letter, or should I just submit this thread?  
Thank you, 
Arthur C. Nicholas

**Comment by karl-project-review** [comment]
Assuming you completed all the other course materials, you should receive a certificate of completion within a few weeks after the end date for your course. Below is a link to the Codecademy FAQ page about this:
https://help.codecademy.com/hc/en-us/articles/115001440488-Earning-a-Credential-of-Completion
Thanks for choosing Codecademy, and good luck as you move forward with SQL!
